### ISSUE TITLE
GSB header reader can seek by wrong amount

### ISSUE THREAD

**Issue by ramain** [mhvk/baseband#54] opened 2017-06-06 17:14 UTC
GSB header reading seeks based on the number of characters in the first line of the .timestamp file,  and will seek to the wrong point when the line lengths change.  This can regularly happen in GMRT headers, as the second last value increases incrementally - I noticed this as an assertion error when it changed from 9999 to 10000, increasing the line length by one character.  I've adjusted the whitespace padding in the timestamp file to create uniform line lengths as a temporary workaround.

**Comment by mhvk** [comment] 2017-06-06 20:08
Hmm, I thought I had this covered. But it may well be better to just read the whole timestamp file in as text mode.

**Comment by ramain** [comment] 2017-06-08 01:25
@mhvk that may be a better solution, especially given the tiny size of the timestamp files.  I found a different header seek error much further in the file, at an inexplicable point (sequence number 25896, with the number of characters in a line unchanging).  At this point, the seek_offset in gsb/header.py no longer returns the correct number (i.e., n is correct, size is correct, but returning n*size is off by one).

**Comment by mhvk** [comment] 2017-06-08 07:15
@ramain - can you point me to the original timestamp file? I'm still surprised that it didn't work...

**Comment by mhvk** [comment] 2017-06-12 18:46
> The GMRT data are on the BGQ at 
> /scratch/m/mhvk/ramain/GMRT-j1810/GMRT/26jul2013/ , the timestamp file 
> in question is j1810+1744.raw.timestamp

@ramain - Do you have the original of that file still? With the edits, I don't know what I'm trying to reproduce...

Though I do think I found the bug; the sequence number seems to be assumed to increase only every 8 subints, while in reality they increase just every sequence (at least in your file, as well as in the Crab). This is the problem with the GSB tests all being internal rather than on real files.

@cczhu - do you want to have an independent look? The relevant problematic code is in `GSBPhasedHeader.seek_offset`

**Comment by ramain** [comment] 2017-06-12 18:58
@mhvk I should have been more explicit, the file listed above is an exact copy of the original. I reverted the whitespace edits once I noticed there were still errors with seek_offset.

**Comment by mhvk** [comment] 2017-06-12 19:53
OK, then part of the problem at least is that there is an extra space at the end of every line -- I now see that the other files in this directory have the same issue -- and in fact that all files seem to have this problem. I'll look a bit further...

**Comment by cczhu** [comment] 2017-06-26 06:01
Sorry for the long delay - I confirmed Marten's suspicion that assumptions made in `GSBPhasedHeader.seek_offset` are the culprit.  Rob, I have hacked Baseband so that you can read your original raw files (and any other files that have only one subint) as a stopgap measure - I'll send you a download link over Slack).  Not sure how to generalise the solution.  We could read a bunch of headers in to determine the number of subints upon first loading the header, and then pass this information (as we do with edv in VDIF) to __init__ each time we make a new header, but there's no guarantee the user or other parts of the code will pass the right info.

**Comment by mhvk** [comment] 2017-08-09 20:46
This was fixed by #60, I think, so I'll close. Do reopen if current master still has problems!

p.s.  One can auto-close by putting `fixes #nnn` in the commit message or in the first comment box on github.

**Closed by mhvk** 2017-08-09 20:46 UTC
